### PR TITLE
ES-3-adding-models

### PR DESCRIPTION
**Pull request by ezAldinWaez**

### CODE REVIEW

**Comment by Ahmad-Mohammad-Kouja** [comment]
@ezAldinWaez  please add the fillable to each model

**Comment by ezAldinWaez** [comment]
> @ezAldinWaez  please add the fillable to each model

@Ahmad-Mohammad-Kouja OK 👍🏻

**Comment by ezAldinWaez** [comment]
> @ezAldinWaez please add the fillable to each model

@Ahmad-Mohammad-Kouja Done.

**Comment by Ahmad-Mohammad-Kouja** [comment]
@ezAldinWaez  thanks
go ahead for the next task

**Pull request merged**
