### PR TITLE
Authentication-features-with-breeze

### PR DESCRIPTION
**Pull request by ezAldinWaez**
install breeze and customize it to fit with the project, fix some problems, and refactor the code.

### CODE REVIEW

**Comment by Ahmad-Mohammad-Kouja** [comment]
@ezAldinWaez  remove any code related to verify email, register and reset password

**Comment by ezAldinWaez** [comment]
ok 👍🏻

**Comment by ezAldinWaez** [comment]
@Ahmad-Mohammad-Kouja Done 👍🏻

**Comment by Ahmad-Mohammad-Kouja** [comment]
@ezAldinWaez  thanks

**Pull request merged**
